[package]
name = "minifi-native-rs-example-extension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# This processor depends on our safe `minifi` wrapper crate.
minifi-native = { path = "../minifi-native-rs" }
ctor = "0.2"